# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI_final.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
## scope 화면 start 버튼 추가, 오타난 변수명 변경 , 보드레이트 default 값 세팅 완료 
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QFrame, QHeaderView, QLabel, QLineEdit,
    QListView, QMainWindow, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1050, 650)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1050, 650))
        MainWindow.setMaximumSize(QSize(1050, 650))
        font = QFont()
        font.setPointSize(10)
        font.setWeight(QFont.Black)
        font.setUnderline(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color : rgb(240, 239, 243);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(10)
        self.centralwidget.setFont(font1)
        self.con_status_lbl = QLabel(self.centralwidget)
        self.con_status_lbl.setObjectName(u"con_status_lbl")
        self.con_status_lbl.setGeometry(QRect(523, 3, 521, 31))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.con_status_lbl.setFont(font2)
        self.con_status_lbl.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.con_status_lbl.setMargin(5)
        self.menu_home_btn = QPushButton(self.centralwidget)
        self.menu_home_btn.setObjectName(u"menu_home_btn")
        self.menu_home_btn.setGeometry(QRect(2, 1, 111, 30))
        self.menu_scope_btn = QPushButton(self.centralwidget)
        self.menu_scope_btn.setObjectName(u"menu_scope_btn")
        self.menu_scope_btn.setGeometry(QRect(286, 1, 111, 30))
        self.menu_parameter_btn = QPushButton(self.centralwidget)
        self.menu_parameter_btn.setObjectName(u"menu_parameter_btn")
        self.menu_parameter_btn.setGeometry(QRect(121, 1, 151, 30))
        self.menu_about_btn = QPushButton(self.centralwidget)
        self.menu_about_btn.setObjectName(u"menu_about_btn")
        self.menu_about_btn.setGeometry(QRect(410, 1, 101, 30))
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(108, -10, 20, 41))
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.centralwidget)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(270, -10, 20, 41))
        self.line_11.setFrameShape(QFrame.VLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.line_13 = QFrame(self.centralwidget)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(395, -10, 20, 41))
        self.line_13.setFrameShape(QFrame.VLine)
        self.line_13.setFrameShadow(QFrame.Sunken)
        self.line_12 = QFrame(self.centralwidget)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(504, -4, 31, 41))
        self.line_12.setFrameShape(QFrame.VLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.stackedWidget_Pages = QStackedWidget(self.centralwidget)
        self.stackedWidget_Pages.setObjectName(u"stackedWidget_Pages")
        self.stackedWidget_Pages.setGeometry(QRect(3, 40, 1051, 601))
        self.Main_Page = QWidget()
        self.Main_Page.setObjectName(u"Main_Page")
        self.label_41 = QLabel(self.Main_Page)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(556, 548, 191, 21))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI Semibold"])
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setUnderline(True)
        self.label_41.setFont(font3)
        self.label_41.setAlignment(Qt.AlignCenter)
        self.label_42 = QLabel(self.Main_Page)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(525, 287, 511, 21))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setWeight(QFont.DemiBold)
        self.label_42.setFont(font4)
        self.label_42.setAlignment(Qt.AlignCenter)
        self.label_43 = QLabel(self.Main_Page)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(840, 145, 81, 21))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setUnderline(True)
        self.label_43.setFont(font5)
        self.label_44 = QLabel(self.Main_Page)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(562, 335, 171, 21))
        self.label_44.setFont(font5)
        self.line_27 = QFrame(self.Main_Page)
        self.line_27.setObjectName(u"line_27")
        self.line_27.setGeometry(QRect(513, 276, 541, 16))
        self.line_27.setStyleSheet(u"border-top: 1px dashed #000000;")
        self.line_27.setFrameShape(QFrame.HLine)
        self.line_27.setFrameShadow(QFrame.Sunken)
        self.target_pos_txt_3 = QLineEdit(self.Main_Page)
        self.target_pos_txt_3.setObjectName(u"target_pos_txt_3")
        self.target_pos_txt_3.setGeometry(QRect(753, 335, 121, 21))
        self.target_pos_txt_3.setStyleSheet(u"background-color : white;\n"
"border : 1px solid black;\n"
"")
        self.label_45 = QLabel(self.Main_Page)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(554, 462, 191, 21))
        self.label_45.setFont(font3)
        self.label_45.setAlignment(Qt.AlignCenter)
        self.max_vel_btn_3 = QPushButton(self.Main_Page)
        self.max_vel_btn_3.setObjectName(u"max_vel_btn_3")
        self.max_vel_btn_3.setGeometry(QRect(893, 375, 75, 24))
        self.label_46 = QLabel(self.Main_Page)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(553, 87, 61, 21))
        self.label_46.setFont(font5)
        self.label_47 = QLabel(self.Main_Page)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(553, 130, 61, 21))
        self.label_47.setFont(font5)
        self.verticalLayoutWidget_15 = QWidget(self.Main_Page)
        self.verticalLayoutWidget_15.setObjectName(u"verticalLayoutWidget_15")
        self.verticalLayoutWidget_15.setGeometry(QRect(623, 166, 171, 31))
        self.verticalLayout_25 = QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_25.setObjectName(u"verticalLayout_25")
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.frame_14 = QFrame(self.verticalLayoutWidget_15)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setStyleSheet(u"background-color:white;")
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.line_29 = QFrame(self.frame_14)
        self.line_29.setObjectName(u"line_29")
        self.line_29.setGeometry(QRect(70, -10, 20, 41))
        self.line_29.setStyleSheet(u"border-right: 1px dashed #000000;")
        self.line_29.setFrameShape(QFrame.VLine)
        self.line_29.setFrameShadow(QFrame.Sunken)
        self.order_current_lbl_5 = QLabel(self.frame_14)
        self.order_current_lbl_5.setObjectName(u"order_current_lbl_5")
        self.order_current_lbl_5.setGeometry(QRect(4, 5, 71, 21))
        self.order_current_lbl_5.setAlignment(Qt.AlignCenter)
        self.real_current_lbl_5 = QLabel(self.frame_14)
        self.real_current_lbl_5.setObjectName(u"real_current_lbl_5")
        self.real_current_lbl_5.setGeometry(QRect(94, 4, 71, 21))
        self.real_current_lbl_5.setAlignment(Qt.AlignCenter)

        self.verticalLayout_25.addWidget(self.frame_14)

        self.label_48 = QLabel(self.Main_Page)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(554, 504, 191, 21))
        self.label_48.setFont(font3)
        self.label_48.setAlignment(Qt.AlignCenter)
        self.servo_on_btn_3 = QPushButton(self.Main_Page)
        self.servo_on_btn_3.setObjectName(u"servo_on_btn_3")
        self.servo_on_btn_3.setGeometry(QRect(809, 458, 75, 24))
        self.acc_dc_txt = QLineEdit(self.Main_Page)
        self.acc_dc_txt.setObjectName(u"acc_dc_txt")
        self.acc_dc_txt.setGeometry(QRect(753, 415, 121, 21))
        self.acc_dc_txt.setStyleSheet(u"background-color : white;\n"
"border : 1px solid black;\n"
"")
        self.max_vel_txt_3 = QLineEdit(self.Main_Page)
        self.max_vel_txt_3.setObjectName(u"max_vel_txt_3")
        self.max_vel_txt_3.setGeometry(QRect(753, 375, 121, 21))
        self.max_vel_txt_3.setStyleSheet(u"background-color : white;\n"
"border : 1px solid black;\n"
"")
        self.label_49 = QLabel(self.Main_Page)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(623, 60, 81, 16))
        self.label_49.setAlignment(Qt.AlignCenter)
        self.target_pos_btn_3 = QPushButton(self.Main_Page)
        self.target_pos_btn_3.setObjectName(u"target_pos_btn_3")
        self.target_pos_btn_3.setGeometry(QRect(893, 335, 75, 24))
        self.acc_dc_btn_3 = QPushButton(self.Main_Page)
        self.acc_dc_btn_3.setObjectName(u"acc_dc_btn_3")
        self.acc_dc_btn_3.setGeometry(QRect(893, 415, 75, 24))
        self.label_50 = QLabel(self.Main_Page)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(524, 4, 511, 21))
        self.label_50.setFont(font4)
        self.label_50.setAlignment(Qt.AlignCenter)
        self.servo_lbl_3 = QLabel(self.Main_Page)
        self.servo_lbl_3.setObjectName(u"servo_lbl_3")
        self.servo_lbl_3.setGeometry(QRect(933, 55, 61, 31))
        self.servo_lbl_3.setStyleSheet(u"background-color: #f0f0f0; /* \ubc30\uacbd\uc0c9 */\n"
"border: 1px solid black; /* \ud14c\ub450\ub9ac \uc0c9\uc0c1\uacfc \ub450\uaed8 */\n"
"border-radius: 10px; /* \ud14c\ub450\ub9ac \ub465\uadfc \ubaa8\uc11c\ub9ac */")
        self.servo_lbl_3.setAlignment(Qt.AlignCenter)
        self.alarm_reset_btn_3 = QPushButton(self.Main_Page)
        self.alarm_reset_btn_3.setObjectName(u"alarm_reset_btn_3")
        self.alarm_reset_btn_3.setGeometry(QRect(809, 500, 160, 24))
        self.label_55 = QLabel(self.Main_Page)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(713, 60, 81, 16))
        self.label_55.setAlignment(Qt.AlignCenter)
        self.homing_home_btn_3 = QPushButton(self.Main_Page)
        self.homing_home_btn_3.setObjectName(u"homing_home_btn_3")
        self.homing_home_btn_3.setGeometry(QRect(809, 543, 160, 24))
        self.verticalLayoutWidget_20 = QWidget(self.Main_Page)
        self.verticalLayoutWidget_20.setObjectName(u"verticalLayoutWidget_20")
        self.verticalLayoutWidget_20.setGeometry(QRect(623, 124, 171, 31))
        self.verticalLayout_26 = QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_26.setObjectName(u"verticalLayout_26")
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.frame_15 = QFrame(self.verticalLayoutWidget_20)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setStyleSheet(u"background-color:white;")
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.line_32 = QFrame(self.frame_15)
        self.line_32.setObjectName(u"line_32")
        self.line_32.setGeometry(QRect(70, -10, 20, 41))
        self.line_32.setStyleSheet(u"border-right: 1px dashed #000000;")
        self.line_32.setFrameShape(QFrame.VLine)
        self.line_32.setFrameShadow(QFrame.Sunken)
        self.order_vel_lbl_5 = QLabel(self.frame_15)
        self.order_vel_lbl_5.setObjectName(u"order_vel_lbl_5")
        self.order_vel_lbl_5.setGeometry(QRect(4, 5, 71, 21))
        self.order_vel_lbl_5.setAlignment(Qt.AlignCenter)
        self.real_vel_lbl_5 = QLabel(self.frame_15)
        self.real_vel_lbl_5.setObjectName(u"real_vel_lbl_5")
        self.real_vel_lbl_5.setGeometry(QRect(94, 4, 71, 21))
        self.real_vel_lbl_5.setAlignment(Qt.AlignCenter)

        self.verticalLayout_26.addWidget(self.frame_15)

        self.label_56 = QLabel(self.Main_Page)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(562, 375, 171, 21))
        self.label_56.setFont(font5)
        self.label_57 = QLabel(self.Main_Page)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(840, 102, 81, 21))
        self.label_57.setFont(font5)
        self.label_58 = QLabel(self.Main_Page)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(562, 415, 171, 21))
        self.label_58.setFont(font5)
        self.Connection_tabWidget = QTabWidget(self.Main_Page)
        self.Connection_tabWidget.setObjectName(u"Connection_tabWidget")
        self.Connection_tabWidget.setGeometry(QRect(4, 6, 501, 591))
        self.Connection_tabWidget.setFont(font4)
        self.Connection_tabWidget.setTabShape(QTabWidget.Triangular)
        self.Connection_tabWidget.setIconSize(QSize(20, 20))
        self.Con_tab_4 = QWidget()
        self.Con_tab_4.setObjectName(u"Con_tab_4")
        self.Con_tab_4.setFont(font1)
        self.label_59 = QLabel(self.Con_tab_4)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 10, 471, 31))
        font6 = QFont()
        font6.setPointSize(10)
        font6.setWeight(QFont.Black)
        self.label_59.setFont(font6)
        self.label_59.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_37 = QFrame(self.Con_tab_4)
        self.line_37.setObjectName(u"line_37")
        self.line_37.setGeometry(QRect(0, 41, 481, 16))
        self.line_37.setStyleSheet(u"border-top: 1px dashed #000000;")
        self.line_37.setFrameShape(QFrame.HLine)
        self.line_37.setFrameShadow(QFrame.Sunken)
        self.verticalLayoutWidget_21 = QWidget(self.Con_tab_4)
        self.verticalLayoutWidget_21.setObjectName(u"verticalLayoutWidget_21")
        self.verticalLayoutWidget_21.setGeometry(QRect(20, 160, 91, 41))
        self.verticalLayoutWidget_21.setFont(font1)
        self.verticalLayout_27 = QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_27.setObjectName(u"verticalLayout_27")
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.label_60 = QLabel(self.verticalLayoutWidget_21)
        self.label_60.setObjectName(u"label_60")
        font7 = QFont()
        font7.setPointSize(11)
        font7.setUnderline(True)
        self.label_60.setFont(font7)
        self.label_60.setAlignment(Qt.AlignCenter)
        self.label_60.setMargin(5)

        self.verticalLayout_27.addWidget(self.label_60)

        self.verticalLayoutWidget_22 = QWidget(self.Con_tab_4)
        self.verticalLayoutWidget_22.setObjectName(u"verticalLayoutWidget_22")
        self.verticalLayoutWidget_22.setGeometry(QRect(20, 300, 91, 41))
        self.verticalLayoutWidget_22.setFont(font1)
        self.verticalLayout_28 = QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_28.setObjectName(u"verticalLayout_28")
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.label_61 = QLabel(self.verticalLayoutWidget_22)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setFont(font7)
        self.label_61.setAlignment(Qt.AlignCenter)
        self.label_61.setMargin(5)

        self.verticalLayout_28.addWidget(self.label_61)

        self.verticalLayoutWidget_23 = QWidget(self.Con_tab_4)
        self.verticalLayoutWidget_23.setObjectName(u"verticalLayoutWidget_23")
        self.verticalLayoutWidget_23.setGeometry(QRect(140, 160, 201, 41))
        self.verticalLayout_29 = QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_29.setObjectName(u"verticalLayout_29")
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.port_comboBox_4 = QComboBox(self.verticalLayoutWidget_23)
        self.port_comboBox_4.addItem("")
        self.port_comboBox_4.addItem("")
        self.port_comboBox_4.addItem("")
        self.port_comboBox_4.addItem("")
        self.port_comboBox_4.addItem("")
        self.port_comboBox_4.addItem("")
        self.port_comboBox_4.setObjectName(u"port_comboBox_4")
        self.port_comboBox_4.setFont(font1)

        self.verticalLayout_29.addWidget(self.port_comboBox_4)

        self.verticalLayoutWidget_24 = QWidget(self.Con_tab_4)
        self.verticalLayoutWidget_24.setObjectName(u"verticalLayoutWidget_24")
        self.verticalLayoutWidget_24.setGeometry(QRect(140, 300, 201, 41))
        self.verticalLayout_30 = QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_30.setObjectName(u"verticalLayout_30")
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.baudrate_comboBox_4 = QComboBox(self.verticalLayoutWidget_24)
        self.baudrate_comboBox_4.addItem("")
        self.baudrate_comboBox_4.addItem("")
        self.baudrate_comboBox_4.addItem("")
        self.baudrate_comboBox_4.addItem("")
        self.baudrate_comboBox_4.setObjectName(u"baudrate_comboBox_4")
        self.baudrate_comboBox_4.setFont(font1)

        self.verticalLayout_30.addWidget(self.baudrate_comboBox_4)

        self.refresh_btn_4 = QPushButton(self.Con_tab_4)
        self.refresh_btn_4.setObjectName(u"refresh_btn_4")
        self.refresh_btn_4.setGeometry(QRect(360, 168, 99, 26))
        self.refresh_btn_4.setFont(font1)
        self.connect_btn_4 = QPushButton(self.Con_tab_4)
        self.connect_btn_4.setObjectName(u"connect_btn_4")
        self.connect_btn_4.setGeometry(QRect(363, 308, 99, 26))
        self.connect_btn_4.setFont(font1)
        self.disconnect_btn_5 = QPushButton(self.Con_tab_4)
        self.disconnect_btn_5.setObjectName(u"disconnect_btn_5")
        self.disconnect_btn_5.setGeometry(QRect(363, 304, 99, 30))
        self.disconnect_btn_5.setFont(font1)
        self.label_5 = QLabel(self.Con_tab_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(4, 43, 491, 31))
        font8 = QFont()
        font8.setPointSize(9)
        font8.setBold(False)
        font8.setUnderline(True)
        self.label_5.setFont(font8)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.Connection_tabWidget.addTab(self.Con_tab_4, "")
        self.Guide_tab_4 = QWidget()
        self.Guide_tab_4.setObjectName(u"Guide_tab_4")
        self.label_62 = QLabel(self.Guide_tab_4)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(10, 10, 481, 31))
        self.label_62.setFont(font6)
        self.label_62.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_38 = QFrame(self.Guide_tab_4)
        self.line_38.setObjectName(u"line_38")
        self.line_38.setGeometry(QRect(0, 41, 491, 16))
        self.line_38.setStyleSheet(u"border-top: 1px dashed #000000;")
        self.line_38.setFrameShape(QFrame.HLine)
        self.line_38.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.Guide_tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(4, 43, 491, 31))
        self.label_4.setFont(font8)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.Connection_tabWidget.addTab(self.Guide_tab_4, "")
        self.servo_off_btn_3 = QPushButton(self.Main_Page)
        self.servo_off_btn_3.setObjectName(u"servo_off_btn_3")
        self.servo_off_btn_3.setGeometry(QRect(893, 458, 75, 24))
        self.line_39 = QFrame(self.Main_Page)
        self.line_39.setObjectName(u"line_39")
        self.line_39.setGeometry(QRect(517, 30, 541, 16))
        self.line_39.setStyleSheet(u"border-top: 1px dashed #000000;")
        self.line_39.setFrameShape(QFrame.HLine)
        self.line_39.setFrameShadow(QFrame.Sunken)
        self.homing_sts_lbl_3 = QLabel(self.Main_Page)
        self.homing_sts_lbl_3.setObjectName(u"homing_sts_lbl_3")
        self.homing_sts_lbl_3.setGeometry(QRect(933, 137, 61, 31))
        self.homing_sts_lbl_3.setStyleSheet(u"background-color: #f0f0f0; /* \ubc30\uacbd\uc0c9 */\n"
"border: 1px solid black; /* \ud14c\ub450\ub9ac \uc0c9\uc0c1\uacfc \ub450\uaed8 */\n"
"border-radius: 10px; /* \ud14c\ub450\ub9ac \ub465\uadfc \ubaa8\uc11c\ub9ac */")
        self.homing_sts_lbl_3.setAlignment(Qt.AlignCenter)
        self.label_63 = QLabel(self.Main_Page)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(840, 63, 81, 21))
        self.label_63.setFont(font5)
        self.line_40 = QFrame(self.Main_Page)
        self.line_40.setObjectName(u"line_40")
        self.line_40.setGeometry(QRect(512, -5, 531, 16))
        self.line_40.setFrameShape(QFrame.HLine)
        self.line_40.setFrameShadow(QFrame.Sunken)
        self.inpos_lbl_3 = QLabel(self.Main_Page)
        self.inpos_lbl_3.setObjectName(u"inpos_lbl_3")
        self.inpos_lbl_3.setGeometry(QRect(933, 96, 61, 31))
        self.inpos_lbl_3.setStyleSheet(u"background-color: #f0f0f0; /* \ubc30\uacbd\uc0c9 */\n"
"border: 1px solid black; /* \ud14c\ub450\ub9ac \uc0c9\uc0c1\uacfc \ub450\uaed8 */\n"
"border-radius: 10px; /* \ud14c\ub450\ub9ac \ub465\uadfc \ubaa8\uc11c\ub9ac */")
        self.inpos_lbl_3.setAlignment(Qt.AlignCenter)
        self.verticalLayoutWidget_25 = QWidget(self.Main_Page)
        self.verticalLayoutWidget_25.setObjectName(u"verticalLayoutWidget_25")
        self.verticalLayoutWidget_25.setGeometry(QRect(623, 84, 171, 31))
        self.verticalLayout_31 = QVBoxLayout(self.verticalLayoutWidget_25)
        self.verticalLayout_31.setObjectName(u"verticalLayout_31")
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.frame_16 = QFrame(self.verticalLayoutWidget_25)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setStyleSheet(u"background-color:white;")
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.line_41 = QFrame(self.frame_16)
        self.line_41.setObjectName(u"line_41")
        self.line_41.setGeometry(QRect(340, 0, 20, 41))
        self.line_41.setStyleSheet(u"border-right: 1px dashed #000000;")
        self.line_41.setFrameShape(QFrame.VLine)
        self.line_41.setFrameShadow(QFrame.Sunken)
        self.order_pos_lbl_5 = QLabel(self.frame_16)
        self.order_pos_lbl_5.setObjectName(u"order_pos_lbl_5")
        self.order_pos_lbl_5.setGeometry(QRect(4, 5, 71, 21))
        self.order_pos_lbl_5.setAlignment(Qt.AlignCenter)
        self.real_pos_lbl_5 = QLabel(self.frame_16)
        self.real_pos_lbl_5.setObjectName(u"real_pos_lbl_5")
        self.real_pos_lbl_5.setGeometry(QRect(94, 4, 71, 21))
        self.real_pos_lbl_5.setAlignment(Qt.AlignCenter)
        self.line_42 = QFrame(self.frame_16)
        self.line_42.setObjectName(u"line_42")
        self.line_42.setGeometry(QRect(70, -10, 20, 51))
        self.line_42.setStyleSheet(u"border-right: 1px dashed #000000;")
        self.line_42.setFrameShape(QFrame.VLine)
        self.line_42.setFrameShadow(QFrame.Sunken)

        self.verticalLayout_31.addWidget(self.frame_16)

        self.label_64 = QLabel(self.Main_Page)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(553, 172, 61, 21))
        self.label_64.setFont(font5)
        self.Dataframe_lbl_3 = QLabel(self.Main_Page)
        self.Dataframe_lbl_3.setObjectName(u"Dataframe_lbl_3")
        self.Dataframe_lbl_3.setGeometry(QRect(524, 219, 521, 51))
        self.Dataframe_lbl_3.setFont(font4)
        self.Dataframe_lbl_3.setStyleSheet(u"    background-color: #f0f0f0; /* \ubc30\uacbd\uc0c9 */\n"
"    border: 1px solid black; /* \ud14c\ub450\ub9ac \uc0c9\uc0c1\uacfc \ub450\uaed8 */\n"
"    border-radius: 5px; /* \ud14c\ub450\ub9ac \ub465\uadfc \ubaa8\uc11c\ub9ac */")
        self.Dataframe_lbl_3.setAlignment(Qt.AlignCenter)
        self.line_43 = QFrame(self.Main_Page)
        self.line_43.setObjectName(u"line_43")
        self.line_43.setGeometry(QRect(508, 5, 16, 581))
        self.line_43.setFrameShape(QFrame.VLine)
        self.line_43.setFrameShadow(QFrame.Sunken)
        self.requset_lbl_home = QLabel(self.Main_Page)
        self.requset_lbl_home.setObjectName(u"requset_lbl_home")
        self.requset_lbl_home.setGeometry(QRect(530, 222, 511, 20))
        self.response_lbl_home = QLabel(self.Main_Page)
        self.response_lbl_home.setObjectName(u"response_lbl_home")
        self.response_lbl_home.setGeometry(QRect(530, 246, 511, 20))
        self.label_51 = QLabel(self.Main_Page)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(841, 183, 81, 21))
        self.label_51.setFont(font5)
        self.alarm__sts_lbl_4 = QLabel(self.Main_Page)
        self.alarm__sts_lbl_4.setObjectName(u"alarm__sts_lbl_4")
        self.alarm__sts_lbl_4.setGeometry(QRect(934, 175, 61, 31))
        self.alarm__sts_lbl_4.setStyleSheet(u"background-color: #f0f0f0; /* \ubc30\uacbd\uc0c9 */\n"
"border: 1px solid black; /* \ud14c\ub450\ub9ac \uc0c9\uc0c1\uacfc \ub450\uaed8 */\n"
"border-radius: 10px; /* \ud14c\ub450\ub9ac \ub465\uadfc \ubaa8\uc11c\ub9ac */")
        self.alarm__sts_lbl_4.setAlignment(Qt.AlignCenter)
        self.stackedWidget_Pages.addWidget(self.Main_Page)
        self.Parameter_Page = QWidget()
        self.Parameter_Page.setObjectName(u"Parameter_Page")
        self.parameter_tbl = QTableWidget(self.Parameter_Page)
        if (self.parameter_tbl.columnCount() < 5):
            self.parameter_tbl.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.parameter_tbl.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.parameter_tbl.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.parameter_tbl.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.parameter_tbl.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.parameter_tbl.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        if (self.parameter_tbl.rowCount() < 20):
            self.parameter_tbl.setRowCount(20)
        self.parameter_tbl.setObjectName(u"parameter_tbl")
        self.parameter_tbl.setGeometry(QRect(0, 28, 511, 561))
        self.parameter_tbl.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.parameter_tbl.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.parameter_tbl.setRowCount(20)
        self.parameter_tbl.horizontalHeader().setMinimumSectionSize(10)
        self.parameter_tbl.horizontalHeader().setHighlightSections(False)
        self.parameter_tbl.horizontalHeader().setProperty("showSortIndicator", True)
        self.parameter_tbl.horizontalHeader().setStretchLastSection(True)
        self.parameter_tbl.verticalHeader().setVisible(False)
        self.parameter_tbl.verticalHeader().setProperty("showSortIndicator", True)
        self.parameter_tbl.verticalHeader().setStretchLastSection(False)
        self.read_btn = QPushButton(self.Parameter_Page)
        self.read_btn.setObjectName(u"read_btn")
        self.read_btn.setGeometry(QRect(848, 124, 75, 24))
        self.label_11 = QLabel(self.Parameter_Page)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(598, 124, 61, 21))
        self.label_11.setFont(font5)
        self.addr_txt = QLineEdit(self.Parameter_Page)
        self.addr_txt.setObjectName(u"addr_txt")
        self.addr_txt.setGeometry(QRect(688, 124, 121, 21))
        self.addr_txt.setStyleSheet(u"background-color : white;\n"
"border : 1px solid black;\n"
"")
        self.line_5 = QFrame(self.Parameter_Page)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(513, 61, 541, 16))
        self.line_5.setStyleSheet(u"border-top: 1px dashed #000000;")
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.write_btn = QPushButton(self.Parameter_Page)
        self.write_btn.setObjectName(u"write_btn")
        self.write_btn.setGeometry(QRect(848, 164, 75, 24))
        self.label_6 = QLabel(self.Parameter_Page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(523, 282, 511, 31))
        self.label_6.setFont(font4)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.line_6 = QFrame(self.Parameter_Page)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(513, 273, 541, 16))
        self.line_6.setStyleSheet(u"border-top: 1px dashed #000000;")
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.Dataframe_lbl = QLabel(self.Parameter_Page)
        self.Dataframe_lbl.setObjectName(u"Dataframe_lbl")
        self.Dataframe_lbl.setGeometry(QRect(524, 219, 521, 51))
        self.Dataframe_lbl.setFont(font4)
        self.Dataframe_lbl.setStyleSheet(u"    background-color: #f0f0f0; /* \ubc30\uacbd\uc0c9 */\n"
"    border: 1px solid black; /* \ud14c\ub450\ub9ac \uc0c9\uc0c1\uacfc \ub450\uaed8 */\n"
"    border-radius: 5px; /* \ud14c\ub450\ub9ac \ub465\uadfc \ubaa8\uc11c\ub9ac */")
        self.Dataframe_lbl.setAlignment(Qt.AlignCenter)
        self.content_script_list_view = QListView(self.Parameter_Page)
        self.content_script_list_view.setObjectName(u"content_script_list_view")
        self.content_script_list_view.setGeometry(QRect(511, 316, 535, 273))
        self.content_script_list_view.setStyleSheet(u"background-color : white;\n"
"border-color : gray;")
        self.label_12 = QLabel(self.Parameter_Page)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(598, 164, 61, 21))
        self.label_12.setFont(font5)
        self.val_txt = QLineEdit(self.Parameter_Page)
        self.val_txt.setObjectName(u"val_txt")
        self.val_txt.setGeometry(QRect(688, 164, 121, 21))
        self.val_txt.setStyleSheet(u"background-color : white;\n"
"border : 1px solid black;\n"
"")
        self.setting_sts_lbl = QLabel(self.Parameter_Page)
        self.setting_sts_lbl.setObjectName(u"setting_sts_lbl")
        self.setting_sts_lbl.setGeometry(QRect(923, 37, 111, 21))
        self.setting_sts_lbl.setFont(font4)
        self.setting_sts_lbl.setAlignment(Qt.AlignCenter)
        self.warning_lbl = QLabel(self.Parameter_Page)
        self.warning_lbl.setObjectName(u"warning_lbl")
        self.warning_lbl.setGeometry(QRect(513, 68, 531, 20))
        font9 = QFont()
        font9.setPointSize(10)
        font9.setBold(True)
        font9.setItalic(True)
        self.warning_lbl.setFont(font9)
        self.warning_lbl.setCursor(QCursor(Qt.ForbiddenCursor))
        self.warning_lbl.setStyleSheet(u"color: red;")
        self.warning_lbl.setAlignment(Qt.AlignCenter)
        self.line_8 = QFrame(self.Parameter_Page)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(510, 28, 541, 16))
        self.line_8.setStyleSheet(u"border-top: 1px dashed #000000;")
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(self.Parameter_Page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(515, 33, 521, 21))
        self.label_8.setFont(font4)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.line = QFrame(self.Parameter_Page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-21, -7, 1071, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(self.Parameter_Page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(2, 2, 1051, 21))
        font10 = QFont()
        font10.setPointSize(11)
        font10.setWeight(QFont.DemiBold)
        self.label_9.setFont(font10)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.requset_lbl_parameter = QLabel(self.Parameter_Page)
        self.requset_lbl_parameter.setObjectName(u"requset_lbl_parameter")
        self.requset_lbl_parameter.setGeometry(QRect(530, 222, 511, 20))
        self.response_lbl_parameter = QLabel(self.Parameter_Page)
        self.response_lbl_parameter.setObjectName(u"response_lbl_parameter")
        self.response_lbl_parameter.setGeometry(QRect(530, 246, 511, 20))
        self.stackedWidget_Pages.addWidget(self.Parameter_Page)
        self.Scope_Page = QWidget()
        self.Scope_Page.setObjectName(u"Scope_Page")
        self.vel_real_check = QCheckBox(self.Scope_Page)
        self.vel_real_check.setObjectName(u"vel_real_check")
        self.vel_real_check.setGeometry(QRect(840, 25, 51, 20))
        self.line_2 = QFrame(self.Scope_Page)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(895, -12, 20, 61))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.Scope_Page)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(732, -13, 20, 61))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label = QLabel(self.Scope_Page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(588, 2, 131, 21))
        self.label.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.Scope_Page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(910, 1, 131, 21))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.cur_real_check = QCheckBox(self.Scope_Page)
        self.cur_real_check.setObjectName(u"cur_real_check")
        self.cur_real_check.setGeometry(QRect(993, 25, 51, 20))
        self.label_2 = QLabel(self.Scope_Page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(760, 1, 131, 21))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.pos_real_check = QCheckBox(self.Scope_Page)
        self.pos_real_check.setObjectName(u"pos_real_check")
        self.pos_real_check.setGeometry(QRect(677, 25, 51, 20))
        self.cur_order_check = QCheckBox(self.Scope_Page)
        self.cur_order_check.setObjectName(u"cur_order_check")
        self.cur_order_check.setGeometry(QRect(917, 25, 61, 20))
        self.pos_order_check = QCheckBox(self.Scope_Page)
        self.pos_order_check.setObjectName(u"pos_order_check")
        self.pos_order_check.setGeometry(QRect(598, 25, 61, 20))
        self.vel_order_check = QCheckBox(self.Scope_Page)
        self.vel_order_check.setObjectName(u"vel_order_check")
        self.vel_order_check.setGeometry(QRect(760, 25, 61, 20))
        self.line_14 = QFrame(self.Scope_Page)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(572, -11, 16, 61))
        self.line_14.setFrameShape(QFrame.VLine)
        self.line_14.setFrameShadow(QFrame.Sunken)
        self.line_15 = QFrame(self.Scope_Page)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(-10, 43, 1061, 20))
        self.line_15.setFrameShape(QFrame.HLine)
        self.line_15.setFrameShadow(QFrame.Sunken)
        self.scope_graph_widget = QWidget(self.Scope_Page)
        self.scope_graph_widget.setObjectName(u"scope_graph_widget")
        self.scope_graph_widget.setGeometry(QRect(0, 60, 1041, 541))
        self.scope_menu_widget = QWidget(self.Scope_Page)
        self.scope_menu_widget.setObjectName(u"scope_menu_widget")
        self.scope_menu_widget.setGeometry(QRect(0, 0, 531, 51))
        self.start_scope_btn = QPushButton(self.Scope_Page)
        self.start_scope_btn.setObjectName(u"start_scope_btn")
        self.start_scope_btn.setGeometry(QRect(540, 10, 31, 31))
        sizePolicy.setHeightForWidth(self.start_scope_btn.sizePolicy().hasHeightForWidth())
        self.start_scope_btn.setSizePolicy(sizePolicy)
        font11 = QFont()
        font11.setFamilies([u"Segoe UI Black"])
        font11.setPointSize(15)
        font11.setWeight(QFont.ExtraBold)
        font11.setItalic(False)
        self.start_scope_btn.setFont(font11)
        self.start_scope_btn.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.start_scope_btn.setStyleSheet(u"QPushButton {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: black;\n"
"    border: 1px solid rgb(239, 239, 239);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(243, 243, 243); /* \ub9c8\uc6b0\uc2a4 \ud638\ubc84 \uc0c1\ud0dc\uc77c \ub54c\uc758 \ubc30\uacbd\uc0c9 */  \n"
"    border: 1px solid rgb(218, 218, 218);                      \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 232, 232 );  \n"
"    border: 1px solid rgb(218, 218, 218);                 \n"
"}\n"
"\n"
"\n"
"/*QPushButton {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: red;\n"
"     border: 1px solid rgb(239, 239, 239);    \n"
"}\n"
"QPushButton: hover {\n"
"    background-color: rgb(243, 243, 243);  \n"
"}\n"
"\n"
"QPusheButton : pressed {\n"
"    background-color: rgb(232, 232, 232 );  \n"
"    border: 1px solid rgb(223, 223, 223);                 \n"
"}*/\n"
"")
        self.stop_scope_btn = QPushButton(self.Scope_Page)
        self.stop_scope_btn.setObjectName(u"stop_scope_btn")
        self.stop_scope_btn.setGeometry(QRect(540, 10, 31, 31))
        sizePolicy.setHeightForWidth(self.stop_scope_btn.sizePolicy().hasHeightForWidth())
        self.stop_scope_btn.setSizePolicy(sizePolicy)
        font12 = QFont()
        font12.setFamilies([u"Segoe UI Black"])
        font12.setPointSize(12)
        font12.setWeight(QFont.ExtraBold)
        font12.setItalic(False)
        self.stop_scope_btn.setFont(font12)
        self.stop_scope_btn.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.stop_scope_btn.setStyleSheet(u"QPushButton {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: red;\n"
"    border: 1px solid rgb(239, 239, 239);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(243, 243, 243); /* \ub9c8\uc6b0\uc2a4 \ud638\ubc84 \uc0c1\ud0dc\uc77c \ub54c\uc758 \ubc30\uacbd\uc0c9 */  \n"
"    border: 1px solid rgb(218, 218, 218);                      \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 232, 232 );  \n"
"    border: 1px solid rgb(218, 218, 218);                 \n"
"}\n"
"\n"
"\n"
"/*QPushButton {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: red;\n"
"     border: 1px solid rgb(239, 239, 239);    \n"
"}\n"
"QPushButton: hover {\n"
"    background-color: rgb(243, 243, 243);  \n"
"}\n"
"\n"
"QPusheButton : pressed {\n"
"    background-color: rgb(232, 232, 232 );  \n"
"    border: 1px solid rgb(223, 223, 223);                 \n"
"}*/\n"
"")
        self.stackedWidget_Pages.addWidget(self.Scope_Page)
        self.line_16 = QFrame(self.centralwidget)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(-16, 30, 1071, 16))
        self.line_16.setFrameShape(QFrame.HLine)
        self.line_16.setFrameShadow(QFrame.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget_Pages.setCurrentIndex(0)
        self.Connection_tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"2232 GUI ", None))
        self.con_status_lbl.setText(QCoreApplication.translate("MainWindow", u"\u25cf  Connect Status", None))
        self.menu_home_btn.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.menu_scope_btn.setText(QCoreApplication.translate("MainWindow", u"Scope", None))
        self.menu_parameter_btn.setText(QCoreApplication.translate("MainWindow", u"Parameter Setting", None))
        self.menu_about_btn.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Home                                    : ", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Control", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Home         : ", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Target Position                       :  ", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Servo                                    : ", None))
        self.max_vel_btn_3.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Position  : ", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Velocity  : ", None))
        self.order_current_lbl_5.setText("")
        self.real_current_lbl_5.setText("")
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Alarm                                    : ", None))
        self.servo_on_btn_3.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Order", None))
        self.target_pos_btn_3.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.acc_dc_btn_3.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Monitoting", None))
        self.servo_lbl_3.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.alarm_reset_btn_3.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Actual", None))
        self.homing_home_btn_3.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.order_vel_lbl_5.setText("")
        self.real_vel_lbl_5.setText("")
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Max Velocity                           : ", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Inposition   : ", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Acceleration & Deceleration  : ", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"   Connetion Setting", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Port  :", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Baudrate :", None))
        self.port_comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"COM1", None))
        self.port_comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"COM2", None))
        self.port_comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"COM3", None))
        self.port_comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", u"COM4", None))
        self.port_comboBox_4.setItemText(4, QCoreApplication.translate("MainWindow", u"COM5", None))
        self.port_comboBox_4.setItemText(5, QCoreApplication.translate("MainWindow", u"COM6", None))

        self.baudrate_comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"4800", None))
        self.baudrate_comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"9600", None))
        self.baudrate_comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"19200", None))
        self.baudrate_comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", u"38400", None))

        self.baudrate_comboBox_4.setCurrentText(QCoreApplication.translate("MainWindow", u"19200", None))
        self.refresh_btn_4.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.connect_btn_4.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.disconnect_btn_5.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"You should set everything (like POWER, PORT, BAUDRATE), Connection will be able to well. ", None))
        self.Connection_tabWidget.setTabText(self.Connection_tabWidget.indexOf(self.Con_tab_4), QCoreApplication.translate("MainWindow", u"Connetion Setting", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"   Connetion Guide", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"You should set everything (like POWER, PORT, BAUDRATE), Connection will be able to well. ", None))
        self.Connection_tabWidget.setTabText(self.Connection_tabWidget.indexOf(self.Guide_tab_4), QCoreApplication.translate("MainWindow", u"Connection Guide", None))
        self.servo_off_btn_3.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.homing_sts_lbl_3.setText("")
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"Servo           : ", None))
        self.inpos_lbl_3.setText("")
        self.order_pos_lbl_5.setText("")
        self.real_pos_lbl_5.setText("")
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Current  : ", None))
        self.Dataframe_lbl_3.setText("")
        self.requset_lbl_home.setText(QCoreApplication.translate("MainWindow", u"Request : ", None))
        self.response_lbl_home.setText(QCoreApplication.translate("MainWindow", u"Response :", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Alarm         : ", None))
        self.alarm__sts_lbl_4.setText("")
        ___qtablewidgetitem = self.parameter_tbl.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Address", None));
        ___qtablewidgetitem1 = self.parameter_tbl.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Content", None));
        ___qtablewidgetitem2 = self.parameter_tbl.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Range", None));
        ___qtablewidgetitem3 = self.parameter_tbl.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Value", None));
        ___qtablewidgetitem4 = self.parameter_tbl.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Default", None));
        self.read_btn.setText(QCoreApplication.translate("MainWindow", u"read", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Address  : ", None))
        self.write_btn.setText(QCoreApplication.translate("MainWindow", u"write", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Script", None))
        self.Dataframe_lbl.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Value    : ", None))
        self.setting_sts_lbl.setText("")
        self.warning_lbl.setText(QCoreApplication.translate("MainWindow", u"\u203b If you want to use this area, you must stop Control Setting \u203b", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Setting Value", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Parameter", None))
        self.requset_lbl_parameter.setText(QCoreApplication.translate("MainWindow", u"Request : ", None))
        self.response_lbl_parameter.setText(QCoreApplication.translate("MainWindow", u"Response :", None))
        self.vel_real_check.setText(QCoreApplication.translate("MainWindow", u"Real", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u25cf Position", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u25cf Current", None))
        self.cur_real_check.setText(QCoreApplication.translate("MainWindow", u"Real", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u25cf Velocity", None))
        self.pos_real_check.setText(QCoreApplication.translate("MainWindow", u"Real", None))
        self.cur_order_check.setText(QCoreApplication.translate("MainWindow", u"Order", None))
        self.pos_order_check.setText(QCoreApplication.translate("MainWindow", u"Order", None))
        self.vel_order_check.setText(QCoreApplication.translate("MainWindow", u"Order", None))
        self.start_scope_btn.setText(QCoreApplication.translate("MainWindow", u"\u25b6", None))
        self.stop_scope_btn.setText(QCoreApplication.translate("MainWindow", u"\u2551", None))
    # retranslateUi

